### ISSUE TITLE
Error: Empty board shows 1error/1filled cell

### ISSUE THREAD

**Issue by eltonfc** [meikpiep/gauguin#38]
I'm on version 0.14.0. When I satar a new game, with all empty cells and click on the question mark, the bubble shows "1 mistake/1filled cell". I would expect 0/0 on an empty board.

Thanks!

**Comment by meikpiep** [comment]
This leads in another direction, thanks for the details.

**Comment by meikpiep** [comment]
I just released version 0.15.1 containing the fix. It should be online via Google play in a few hours, F-Droid will take 3-6 days to include it in its next build. I will ping here when the release arrives my phone via F-Droid.

**Comment by meikpiep** [comment]
FYI: Version 0.15.1 fixing this issue is now available on F-Droid.

**Comment by eltonfc** [comment]
Thanks! Funny enough, 0.15.1 fixed the display at the top, but didn't fix the mistake counting.

In the following screenshots, I:

1) Started a new game, empty board (shows 1 mistake /1 filled cell)
![Screenshot_20231215-150525](https://github.com/meikpiep/gauguin/assets/44242112/e4d30062-652a-42f4-9069-393603d63482)

2) filled one correct cell (shows 1 mistake/1 filled)
![Screenshot_20231215-150540](https://github.com/meikpiep/gauguin/assets/44242112/9bc223e3-ec15-44ca-9d47-b88c2c081ec4)

3) Filled one cell with a mistake (shows mistake/1 filled cell)
![Screenshot_20231215-150555](https://github.com/meikpiep/gauguin/assets/44242112/f9e46c09-e614-41e5-8754-9e9f9901b182)

4) Filled two correct cells (shows 1 mistake/2 filled)
![Screenshot_20231215-150604](https://github.com/meikpiep/gauguin/assets/44242112/cdd857cf-664c-413c-a5ec-2e0358b63591)

5) Filled two cells, one correct, one mistake (shows 1 mistake/2 filled)
![Screenshot_20231215-150620](https://github.com/meikpiep/gauguin/assets/44242112/da3c0495-a1a3-482d-9cd5-84c6f9abf75e)

6) Filled 2 cells with 2 mistakes (shows 2 mistakes/2 filled)
![Screenshot_20231215-150628](https://github.com/meikpiep/gauguin/assets/44242112/9a2a140b-2ce9-4aad-ac2d-648464387722)


There seems to be some problem with the initialization of these counting variables

I'm running Android 9 on an Asus Zenfone Max Pro (M2) (ASUS_X01BDA).
